(function(){
'use strict';
const STORE='log-test-sharing-v1',KM='kmreg-test-v4-data',ENDPOINT='https://sharon.life/log/api/publish.php';
const VALID=/^[A-Za-z0-9_-]{12}$/;
const read=(key=STORE)=>{try{const v=JSON.parse(localStorage.getItem(key)||'{}');return v&&typeof v==='object'?v:{};}catch(_){return {};}};
const write=v=>localStorage.setItem(STORE,JSON.stringify(v));
function saveRight(id,token){if(!VALID.test(id)||!token)return;const s=read();s.collaboration=s.collaboration&&typeof s.collaboration==='object'?s.collaboration:{};s.collaboration[id]={editToken:String(token),receivedAt:new Date().toISOString()};write(s);}
function removeRight(id){const s=read();if(s.collaboration?.[id]){delete s.collaboration[id];write(s);}return true;}
function right(id){return read().collaboration?.[id]?.editToken||'';}
function canEdit(id){return !!right(id);}
function shareValue(id,token){return JSON.stringify({kind:'log-share',version:1,id,editToken:token});}
function parseShare(value){try{const p=typeof value==='string'?JSON.parse(value):value;return p?.kind==='log-share'&&p.version===1&&VALID.test(p.id)&&typeof p.editToken==='string'&&p.editToken.length>=20?p:null;}catch(_){return null;}}
function localCardForConfig(id){const km=read(KM),cards=Array.isArray(km.cards)?km.cards:[],s=read(),info=s.published?.[id];return cards.find(c=>String(c.id)===String(info?.id))||cards.find(c=>c?.sharedSource?.configurationId===id&&c?.sharedSource?.isRoot)||null;}
function cardBundle(id){const card=localCardForConfig(id);if(!card)throw Error('De lokale kaart voor deze identifier is niet gevonden.');const clean={};for(const k of ['id','name','format','value','color','locationId','scanAction','createdAt','updatedAt'])if(card[k]!==undefined)clean[k]=JSON.parse(JSON.stringify(card[k]));return{schema:'https://sharon.life/log/config/v1',kind:'log-config',id,title:card.name||'Kaart',root:{type:'card',sourceId:String(card?.sharedSource?.sourceId||card.id)},exportedAt:new Date().toISOString(),source:{app:'Log',build:String(window.LOG_TEST_BUILD||'0.38-test')},objects:{locations:[],themes:[],subthemes:[],cards:[clean],actions:[]}};}
async function request(bundle,headers){const response=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json',...headers},body:JSON.stringify(bundle),cache:'no-store'});let result={};try{result=await response.json();}catch(_){}if(!response.ok)throw Error(result.error||`Publiceren mislukt (${response.status}).`);return result;}
async function enable(id){const s=read(),key=String(s.key||'');if(!key)throw Error('De publicatiesleutel ontbreekt op dit apparaat.');const result=await request(cardBundle(id),{'X-Log-Publish-Key':key,'X-Log-Collaboration-Create':'1'});if(result.editToken)saveRight(id,result.editToken);if(!right(id))throw Error('De server gaf geen samenwerkingsrecht terug.');return result;}
async function publishCollaborative(id){const token=right(id);if(!token)throw Error('Voor deze kaart is geen samenwerkingsrecht opgeslagen.');return request(cardBundle(id),{'X-Log-Edit-Token':token});}
async function copy(text){try{await navigator.clipboard.writeText(text);return true;}catch(_){return false;}}
function setNote(note,text){if(note)note.textContent=text;}
function installFetch(){if(window.fetch?.__logCollaboration)return;const native=window.fetch.bind(window),wrapped=async(input,init={})=>{const url=typeof input==='string'?input:input?.url||'',method=String(init.method||input?.method||'GET').toUpperCase();if(url===ENDPOINT&&method==='POST'&&typeof init.body==='string'){let body=null;try{body=JSON.parse(init.body);}catch(_){}if(body?.kind==='log-config'&&VALID.test(body.id)){const headers=new Headers(init.headers||{}),token=right(body.id);if(token&&!headers.get('X-Log-Publish-Key'))headers.set('X-Log-Edit-Token',token);init={...init,headers};}}return native(input,init);};wrapped.__logCollaboration=true;wrapped.__native=native;window.fetch=wrapped;}
function augment(){const d=document.querySelector('dialog.log-public-dialog[open]');if(!d||d.dataset.collaborationAugmented)return;const id=d.querySelector('.log-public-identifier')?.textContent?.trim();if(!VALID.test(id))return;const info=read().published?.[id],card=localCardForConfig(id);if(info?.type!=='card'&&!card?.sharedSource)return;d.dataset.collaborationAugmented='1';const actions=d.querySelector('.log-public-actions'),note=d.querySelector('.log-public-note');if(!actions)return;
const btn=document.createElement('button');btn.type='button';btn.className='btn secondary';btn.textContent=right(id)?'Samenwerkingscode':'Samenwerken';actions.appendChild(btn);btn.onclick=async()=>{btn.disabled=true;try{if(!right(id))await enable(id);const code=shareValue(id,right(id));setNote(note,await copy(code)?'Samenwerkingscode gekopieerd. De ontvanger kan hiermee dezelfde kaart aanpassen en terugpubliceren.':code);btn.textContent='Samenwerkingscode';ensurePublish();ensureStop();}catch(e){setNote(note,e.message);}finally{btn.disabled=false;}};
function ensurePublish(){if(!right(id)||actions.querySelector('[data-collab-publish]'))return;const publish=document.createElement('button');publish.type='button';publish.className='btn';publish.dataset.collabPublish='1';publish.textContent='Wijziging publiceren';actions.appendChild(publish);publish.onclick=async()=>{publish.disabled=true;try{const r=await publishCollaborative(id);setNote(note,`Wijziging gepubliceerd · revisie ${Number(r.revision)||1}.`);publish.textContent='Gepubliceerd';setTimeout(()=>publish.textContent='Wijziging publiceren',1600);}catch(e){setNote(note,e.message);}finally{publish.disabled=false;}};}
function ensureStop(){if(!right(id)||actions.querySelector('[data-collab-stop]'))return;const stop=document.createElement('button');stop.type='button';stop.className='btn secondary';stop.dataset.collabStop='1';stop.textContent='Lokaal schrijfrecht verwijderen';actions.appendChild(stop);stop.onclick=()=>{removeRight(id);setNote(note,'Het lokale samenwerkingsrecht is verwijderd. De gedeelde kaart zelf blijft bestaan.');stop.remove();actions.querySelector('[data-collab-publish]')?.remove();btn.textContent='Samenwerken';};}
ensurePublish();ensureStop();}
function receive(p){saveRight(p.id,p.editToken);const ui=window.LogCardsUI;if(ui?.sheet){const panel=ui.sheet('Samenwerking ontvangen',`<p>Je mag wijzigingen publiceren voor gedeelde kaart <strong>${p.id}</strong>.</p><p>Haal de kaart met dezelfde identifier op wanneer die nog niet lokaal aanwezig is. Daarna verschijnt bij de gedeelde kaart de mogelijkheid om wijzigingen te publiceren.</p><button class="btn full" data-collab-close>Sluiten</button>`);panel.querySelector('[data-collab-close]').onclick=()=>ui.close();return panel;}return p;}
function installScanner(){const timer=setInterval(()=>{const api=window.LogCode;if(!api?.parse||api.parse.__collaboration)return;const original=api.parse.bind(api);const wrapped=value=>{const p=parseShare(value);if(p)return p;return original(value);};wrapped.__collaboration=true;api.parse=wrapped;if(api.preview&&!api.preview.__collaboration){const old=api.preview.bind(api),preview=p=>p?.kind==='log-share'?receive(p):old(p);preview.__collaboration=true;api.preview=preview;}clearInterval(timer);},100);setTimeout(()=>clearInterval(timer),15000);}
function install(){window.LOG_TEST_BUILD='0.38-test';installFetch();installScanner();new MutationObserver(augment).observe(document.documentElement,{childList:true,subtree:true});setTimeout(augment,0);window.LogCollaboration={saveRight,removeRight,right,canEdit,shareValue,parseShare,enable,publishCollaborative,receive};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();